language: python
python: ['3.6', '3.5', '2.7']
env:
    matrix:
        - NUMPY_VERSION='==1.14.*' SCIPY_VERSION='==1.0.*'
        - NUMPY_VERSION='==1.14.*' SCIPY_VERSION='==0.19.*'
        - NUMPY_VERSION='==1.13.*' SCIPY_VERSION='==1.0.*'
        - NUMPY_VERSION='==1.13.*' SCIPY_VERSION='==0.19.*'
addons:
    apt:
        packages:
            - libsuitesparse-dev
install:
    - pip install 'setuptools>=18' 'numpy'$NUMPY_VERSION 'scipy'$SCIPY_VERSION
    - pip list
    - python setup.py build_ext --inplace
script: py.test
